#!/usr/bin/env bash

# dreaming_loop.sh - Analyze progress logs and propose rule updates.
# This script reads the last processed timestamp from dreaming-state.md,
# extracts new log entries from progress.md, detects repeated failures,
# drafts a minimal rule addition, suggests deletion of an obsolete rule,
# writes the proposal to proposals/improvement_pr.md, and updates the state.

# Paths (relative to the repository root)
STATE_FILE="dreaming-state.md"
PROGRESS_FILE="progress.md"
RULES_FILE="rules.md"
PROPOSAL_FILE="proposals/improvement_pr.md"

# Ensure required files exist
if [[ ! -f "$STATE_FILE" ]]; then
  echo "State file not found: $STATE_FILE" >&2
  exit 1
fi
if [[ ! -f "$PROGRESS_FILE" ]]; then
  echo "Progress log not found: $PROGRESS_FILE" >&2
  exit 1
fi
if [[ ! -f "$RULES_FILE" ]]; then
  echo "Rules file not found: $RULES_FILE" >&2
  exit 1
fi

# Read last processed timestamp
last_ts=$(cat "$STATE_FILE" | tr -d '\r')
# Convert to epoch seconds for comparison
last_epoch=$(date -u -d "$last_ts" +%s 2>/dev/null || date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "$last_ts" +%s)
if [[ -z "$last_epoch" ]]; then
  echo "Failed to parse timestamp: $last_ts" >&2
  exit 1
fi

# Parse progress.md for entries newer than last_ts
# We'll collect error messages (normalized) and dates.
declare -A err_counts   # key: normalized error message, value: count
declare -A err_dates    # key: normalized error message, value: space-separated dates
current_date=""
while IFS= read -r line; do
  # Detect heading lines like "## 2026-08-14"
  if [[ $line =~ ^##[[:space:]]([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
    heading_date="${BASH_REMATCH[1]}"
    entry_epoch=$(date -u -d "$heading_date" +%s)
    if (( entry_epoch > last_epoch )); then
      current_date="$heading_date"
    else
      current_date=""
    fi
    continue
  fi

  # If within a newer entry block and line is an error line prefixed with "- ERROR:"
  if [[ -n $current_date && $line == "- ERROR:"* ]]; then
    raw_msg="${line#- ERROR: }"
    # Normalize error message: strip date suffix "on YYYY-MM-DD" and trailing punctuation.
    norm_msg=$(echo "$raw_msg" | sed -E 's/on [0-9]{4}-[0-9]{2}-[0-9]{2}//g' | sed -E 's/[[:punct:]]+$//g' | xargs)
    (( err_counts["$norm_msg"]++ ))
    if [[ -z "${err_dates["$norm_msg"]}" ]]; then
      err_dates["$norm_msg"]="$current_date"
    else
      err_dates["$norm_msg"]+=" $current_date"
    fi
  fi
done < "$PROGRESS_FILE"

# Identify repeated failures (2 or more occurrences)
repeated_errors=()
for msg in "${!err_counts[@]}"; do
  if (( err_counts["$msg"] >= 2 )); then
    repeated_errors+=("$msg")
  fi
done

# Prepare proposal content
{
  echo "# Improvement Proposal"
  echo ""
  if (( ${#repeated_errors[@]} == 0 )); then
    echo "## No repeated failures detected"
    echo "The analysis did not find any error messages occurring two or more times since the last check."
  else
    echo "## Repeated Failures Detected"
    for msg in "${repeated_errors[@]}"; do
      count=${err_counts["$msg"]}
      dates=${err_dates["$msg"]}
      echo "- **Error:** $msg"
      echo "  - Occurrences: $count"
      echo "  - Dates: $dates"
    done
    echo ""
    echo "## Proposed Rule Addition"
    first_msg=${repeated_errors[0]}
    if [[ "$first_msg" == *"API rate limit exceeded"* ]]; then
      echo "- **Rule Name:** RateLimitBackoff"
      echo "- **Description:** When an API rate limit exceeded error occurs, pause with exponential backoff and retry up to 5 times before aborting."
    else
      echo "- **Rule Name:** GenericRetryOnError"
      echo "- **Description:** For the identified repeated error, add a retry with backoff appropriate to the error context."
    fi
    echo ""
  fi

  echo "## Proposed Rule Deletion"
  obsolete_line=$(grep -i "Obsolete" "$RULES_FILE" | head -n1)
  if [[ -n $obsolete_line ]]; then
    if [[ $obsolete_line =~ \*\*([^*]+)\*\* ]]; then
      obsolete_rule="${BASH_REMATCH[1]}"
    else
      obsolete_rule="(Unnamed Obsolete Rule)"
    fi
    echo "- **Rule Name:** $obsolete_rule"
    echo "- **Reason:** Marked as obsolete and has not been triggered in recent runs."
  else
    echo "- No obvious obsolete rule found. Review manually if needed."
  fi

  echo ""
  echo "*Generated by dreaming_loop.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')*"
} > "$PROPOSAL_FILE"

# Update dreaming-state.md with current timestamp
date -u '+%Y-%m-%dT%H:%M:%SZ' > "$STATE_FILE"

exit 0
